[package]
name = "typst-bsuir-core"
version = "1.18.8"
entrypoint = "main.typ"
authors = ["Slavita"]
license = "Unlicense"
description = ""
homepage = ""
repository = ""
keywords = [
    "bsuir",
    "gost",
]
compiler = "0.15.0"
exclude = [
    ".github",
    "docs",
    "tests",
    "assets",
    ".git",
]

[tool.utpm]
